### PR TITLE
Suggestion for a neater DI of db into server api functions

### PR DESCRIPTION
**Pull request by kajism**
https://github.com/danielsz/system-dependency-injection/issues/3

### CODE REVIEW

**Comment by danielsz** [comment]
Excellent work. Thanks, @kajism

**Comment by kajism** [comment]
This was my first PR, I hope it's is not too messy. It is a breaking change, I'm not sure if it's worth it. But the code is simpler.

I have also noticed that this check (included in http-kit and jetty)

``` clojure
    (let [handler (if (instance? App handler)
                    (:app handler)
                    handler)
```

is missing in the component for Immutant server.

I'm wondering that there may be cases, when more then just the db component need to be injected into the app. Maybe this check could be simplified to just using (if -not (fn? handler) instead of (instance?) of this specific record.... Something like this would allow to write custom app components.

**Comment by danielsz** [comment]
That was an excellent PR. It was not messy at all, and it's certainly worth it. It's important to lead the way with emerging best practices. (And any PRs that removes code is a big plus in my eyes.)

**Comment by danielsz** [comment]
Your suggestion to invert the check is also excellent. Instead of checking if we are passing a component, we can check if we are not passing a function, and so presume it is a component, with the added benefit of allowing users to pass custom components. Brilliant!

**Comment by danielsz** [comment]
Hello @kajism, I've implemented your suggestion and also filled in the immutant component. Please feel free to check/test it out and comment on it. Thanks again!

**Comment by kajism** [comment]
Ok, great @danielsz! I'm going to migrate our application under development from lein/no-components to boot/system, so I'll check/test it immediately. Thanks a lot!

**Pull request merged**
